[package]
name = "rust_android_native_activity"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
android_logger = "0.13"
android-activity = { version = "0.4", features = ["native-activity"] }
ndk-sys = "0.4"
ndk = "0.7"

[lib]
crate_type = ["cdylib"]
